In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import linear_model

In [2]:
df=pd.read_csv("D:\Datasets\weatherAUS.csv")

In [3]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [4]:
df=df.drop('Evaporation', axis=1)

In [5]:
df=df.drop('Sunshine', axis=1)

In [6]:
df=df.drop('Cloud9am', axis=1)

In [7]:
df=df.drop('Cloud3pm', axis=1)

In [8]:
df

,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,ESE,ESE,17.0,17.0,62.0,36.0,1020.2,1017.9,15.0,20.9,No,NaN

In [9]:
nan_count = df.isna().sum()
print(nan_count)

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [10]:
df['MinTemp'] = df['MinTemp'].fillna(method='ffill')

In [11]:
df['MaxTemp'] = df['MaxTemp'].fillna(method='ffill')

In [12]:
df = df.dropna(subset=['Rainfall'])

In [13]:
df['WindGustDir'] = df['WindGustDir'].fillna(method='ffill')

C:\Users\gkred\AppData\Local\Temp\ipykernel_24872\725658891.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WindGustDir'] = df['WindGustDir'].fillna(method='ffill')

In [14]:
df['WindGustSpeed'] = df['WindGustSpeed'].fillna(method='ffill')

C:\Users\gkred\AppData\Local\Temp\ipykernel_24872\3326348530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WindGustSpeed'] = df['WindGustSpeed'].fillna(method='ffill')

In [15]:
columns_to_fill = ['WindDir9am', 'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm']
df[columns_to_fill] = df[columns_to_fill].fillna(method='ffill')

C:\Users\gkred\AppData\Local\Temp\ipykernel_24872\1654956822.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[columns_to_fill] = df[columns_to_fill].fillna(method='ffill')

In [16]:
df = df.dropna(subset=['RainTomorrow'])

In [17]:
# checking for any missing values in the data set to get rid of unneSessary training examples
# df['your column name'].isnull().values.any() : this command checks for any nan values in the data frame.
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)
rows_with_NaN = df[row_has_NaN]
print(rows_with_NaN)

Empty DataFrame
Columns: [Date, Location, MinTemp, MaxTemp, Rainfall, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

In [18]:

string_columns=['Location','WindGustDir','WindDir9am','WindDir3pm']

for cat in string_columns:
    print(np.unique(df[cat]))

['Adelaide' 'Albany' 'Albury' 'AliceSprings' 'BadgerysCreek' 'Ballarat'
 'Bendigo' 'Brisbane' 'Cairns' 'Canberra' 'Cobar' 'CoffsHarbour'
 'Dartmoor' 'Darwin' 'GoldCoast' 'Hobart' 'Katherine' 'Launceston'
 'Melbourne' 'MelbourneAirport' 'Mildura' 'Moree' 'MountGambier'
 'MountGinini' 'Newcastle' 'Nhil' 'NorahHead' 'NorfolkIsland' 'Nuriootpa'
 'PearceRAAF' 'Penrith' 'Perth' 'PerthAirport' 'Portland' 'Richmond'
 'Sale' 'SalmonGums' 'Sydney' 'SydneyAirport' 'Townsville' 'Tuggeranong'
 'Uluru' 'WaggaWagga' 'Walpole' 'Watsonia' 'Williamtown' 'Witchcliffe'
 'Wollongong' 'Woomera']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']

In [19]:
import pandas as pd

# Assuming df is your DataFrame containing string columns
# First, identify the columns with string (object) data type
# Perform one-hot encoding on all identified string columns
df_encoded = pd.get_dummies(df, columns=string_columns)

# Now, df_encoded contains the one-hot encoded DataFrame with all string columns encoded.

In [20]:
df_encoded.shape

(140787, 112)

In [21]:
df_encoded

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2008-12-01,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,...,0,0,0,0,0,0,0,0,1,0
1,2008-12-02,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,...,0,0,0,0,0,0,0,0,0,1
2,2008-12-03,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,...,0,0,0,0,0,0,0,0,0,1
3,2008-12-04,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,...,0,0,0,0,0,0,0,0,0,0
4,2008-12-05,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,2017-06-20,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,...,0,0,0,0,0,0,0,0,0,0
145455,2017-06-21,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,...,0,0,0,0,0,0,0,0,0,0
145456,2017-06-22,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,...,0,0,0,0,0,0,0,0,0,0
145457,2017-06-23,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,...,0,0,0,0,0,0,0,0,1,0
145458,2017-06-24,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df_encoded['RainToday']

0         No
1         No
2         No
3         No
4         No
          ..
145454    No
145455    No
145456    No
145457    No
145458    No
Name: RainToday, Length: 140787, dtype: object

In [23]:

# Assuming 'df' is your DataFrame and 'column_name' is the name of the column with 'yes' and 'no'
mapping = {'Yes': 1, 'No': 0}

df_encoded['RainToday'] = df_encoded['RainToday'].map(mapping)

In [24]:
df_encoded['RainToday']

0         0
1         0
2         0
3         0
4         0
         ..
145454    0
145455    0
145456    0
145457    0
145458    0
Name: RainToday, Length: 140787, dtype: int64

In [25]:

# Assuming 'df' is your DataFrame and 'column_name' is the name of the column with 'yes' and 'no'
mapping = {'Yes': 1, 'No': 0}

df_encoded['RainTomorrow'] = df_encoded['RainTomorrow'].map(mapping)

In [26]:
df_encoded['RainTomorrow']

0         0
1         0
2         0
3         0
4         0
         ..
145454    0
145455    0
145456    0
145457    0
145458    0
Name: RainTomorrow, Length: 140787, dtype: int64

In [27]:
raintom=df_encoded['RainTomorrow']

In [29]:
df_encoded.to_csv('weather_encoded.csv', index=False)

In [ ]:
raintom

0         0
1         0
2         0
3         0
4         0
         ..
145454    0
145455    0
145456    0
145457    0
145458    0
Name: RainTomorrow, Length: 140787, dtype: int64

In [ ]:
df_encoded= df_encoded.drop('RainTomorrow', axis=1)

In [ ]:
df_encoded

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2008-12-01,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,...,0,0,0,0,0,0,0,0,1,0
1,2008-12-02,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,...,0,0,0,0,0,0,0,0,0,1
2,2008-12-03,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,...,0,0,0,0,0,0,0,0,0,1
3,2008-12-04,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,...,0,0,0,0,0,0,0,0,0,0
4,2008-12-05,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,2017-06-20,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,...,0,0,0,0,0,0,0,0,0,0
145455,2017-06-21,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,...,0,0,0,0,0,0,0,0,0,0
145456,2017-06-22,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,...,0,0,0,0,0,0,0,0,0,0
145457,2017-06-23,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,...,0,0,0,0,0,0,0,0,1,0
145458,2017-06-24,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
def feature_normalize(X):

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu)/sigma
    return X_norm

In [ ]:
non_cat=['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm']

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame
column_names = df_encoded.columns.tolist()

print(column_names)

['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'Location_Adelaide', 'Location_Albany', 'Location_Albury', 'Location_AliceSprings', 'Location_BadgerysCreek', 'Location_Ballarat', 'Location_Bendigo', 'Location_Brisbane', 'Location_Cairns', 'Location_Canberra', 'Location_Cobar', 'Location_CoffsHarbour', 'Location_Dartmoor', 'Location_Darwin', 'Location_GoldCoast', 'Location_Hobart', 'Location_Katherine', 'Location_Launceston', 'Location_Melbourne', 'Location_MelbourneAirport', 'Location_Mildura', 'Location_Moree', 'Location_MountGambier', 'Location_MountGinini', 'Location_Newcastle', 'Location_Nhil', 'Location_NorahHead', 'Location_NorfolkIsland', 'Location_Nuriootpa', 'Location_PearceRAAF', 'Location_Penrith', 'Location_Perth', 'Location_PerthAirport', 'Location_Portland', 'Location_Richmond', 'Location_Sale', 'Location_SalmonGums', 'Location_Sydney', 'Location_SydneyAirport', 'Location_Townsville', 'Location_Tuggeranong', 'Location_Uluru', 'Location_WaggaWagga', 'Location_Walpole', 'Location_Watsonia', 'Location_Williamtown', 'Location_Witchcliffe', 'Location_Wollongong', 'Location_Woomera', 'WindGustDir_E', 'WindGustDir_ENE', 'WindGustDir_ESE', 'WindGustDir_N', 'WindGustDir_NE', 'WindGustDir_NNE', 'WindGustDir_NNW', 'WindGustDir_NW', 'WindGustDir_S', 'WindGustDir_SE', 'WindGustDir_SSE', 'WindGustDir_SSW', 'WindGustDir_SW', 'WindGustDir_W', 'WindGustDir_WNW', 'WindGustDir_WSW', 'WindDir9am_E', 'WindDir9am_ENE', 'WindDir9am_ESE', 'WindDir9am_N', 'WindDir9am_NE', 'WindDir9am_NNE', 'WindDir9am_NNW', 'WindDir9am_NW', 'WindDir9am_S', 'WindDir9am_SE', 'WindDir9am_SSE', 'WindDir9am_SSW', 'WindDir9am_SW', 'WindDir9am_W', 'WindDir9am_WNW', 'WindDir9am_WSW', 'WindDir3pm_E', 'WindDir3pm_ENE', 'WindDir3pm_ESE', 'WindDir3pm_N', 'WindDir3pm_NE', 'WindDir3pm_NNE', 'WindDir3pm_NNW', 'WindDir3pm_NW', 'WindDir3pm_S', 'WindDir3pm_SE', 'WindDir3pm_SSE', 'WindDir3pm_SSW', 'WindDir3pm_SW', 'WindDir3pm_W', 'WindDir3pm_WNW', 'WindDir3pm_WSW']

In [ ]:
for col in non_cat:
    df_encoded[col]=feature_normalize(df_encoded[col])

In [ ]:
df_encoded

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,2008-12-01,0.189439,-0.047189,-0.206727,0.339244,0.675486,0.572085,0.111853,-1.401624,-1.460486,...,0,0,0,0,0,0,0,0,1,0
1,2008-12-02,-0.747703,0.262022,-0.277606,0.339244,-1.124887,0.351004,-1.290058,-1.258211,-1.044802,...,0,0,0,0,0,0,0,0,0,1
2,2008-12-03,0.111344,0.346352,-0.277606,0.486382,0.562962,0.793166,-1.601594,-1.019190,-1.474820,...,0,0,0,0,0,0,0,0,0,1
3,2008-12-04,-0.466561,0.669618,-0.277606,-1.132137,-0.337224,-1.086022,-1.238135,-1.688449,-0.041427,...,0,0,0,0,0,0,0,0,0,0
4,2008-12-05,0.829820,1.273985,-0.159474,0.118537,-0.787317,0.129923,0.683002,-0.875777,-1.016134,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,2017-06-20,-1.356846,-0.201794,-0.277606,-0.617153,0.112869,-0.643860,-0.511218,-1.162602,0.976283,...,0,0,0,0,0,0,0,0,0,0
145455,2017-06-21,-1.466179,0.023087,-0.277606,-0.617153,-0.112177,-0.864941,-0.926599,-1.306015,0.961949,...,0,0,0,0,0,0,0,0,0,0
145456,2017-06-22,-1.341227,0.290132,-0.277606,-1.279275,-0.112177,-1.086022,-0.666986,-1.449428,0.804276,...,0,0,0,0,0,0,0,0,0,0
145457,2017-06-23,-1.060084,0.515013,-0.277606,-0.175739,-0.562270,-1.086022,-0.822754,-1.306015,0.445927,...,0,0,0,0,0,0,0,0,1,0
145458,2017-06-24,-0.685227,0.529068,-0.277606,-0.837861,-0.112177,-1.307103,-0.926599,-1.306015,0.216584,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame and 'date_column' is the name of the column with dates in YYYY-MM-DD format
df_encoded['Date'] = pd.to_datetime(df_encoded['Date']).dt.strftime('%m')

In [ ]:
df_encoded

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,12,0.189439,-0.047189,-0.206727,0.339244,0.675486,0.572085,0.111853,-1.401624,-1.460486,...,0,0,0,0,0,0,0,0,1,0
1,12,-0.747703,0.262022,-0.277606,0.339244,-1.124887,0.351004,-1.290058,-1.258211,-1.044802,...,0,0,0,0,0,0,0,0,0,1
2,12,0.111344,0.346352,-0.277606,0.486382,0.562962,0.793166,-1.601594,-1.019190,-1.474820,...,0,0,0,0,0,0,0,0,0,1
3,12,-0.466561,0.669618,-0.277606,-1.132137,-0.337224,-1.086022,-1.238135,-1.688449,-0.041427,...,0,0,0,0,0,0,0,0,0,0
4,12,0.829820,1.273985,-0.159474,0.118537,-0.787317,0.129923,0.683002,-0.875777,-1.016134,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,06,-1.356846,-0.201794,-0.277606,-0.617153,0.112869,-0.643860,-0.511218,-1.162602,0.976283,...,0,0,0,0,0,0,0,0,0,0
145455,06,-1.466179,0.023087,-0.277606,-0.617153,-0.112177,-0.864941,-0.926599,-1.306015,0.961949,...,0,0,0,0,0,0,0,0,0,0
145456,06,-1.341227,0.290132,-0.277606,-1.279275,-0.112177,-1.086022,-0.666986,-1.449428,0.804276,...,0,0,0,0,0,0,0,0,0,0
145457,06,-1.060084,0.515013,-0.277606,-0.175739,-0.562270,-1.086022,-0.822754,-1.306015,0.445927,...,0,0,0,0,0,0,0,0,1,0
145458,06,-0.685227,0.529068,-0.277606,-0.837861,-0.112177,-1.307103,-0.926599,-1.306015,0.216584,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_encoded.to_csv('weather_encoded.csv', index=False)

In [ ]:

# Assuming 'df' is your DataFrame and 'column_name' is the name of the column with 'yes' and 'no'
mapp = {'12': 'Dec', '11': 'Nov','10':'Oct','09':'Sep','08':'Aug','07':'Jul','06':'Jun','05':'May','04':'Apr','03':'Mar','02':'Feb','01':'Jan'}

df_encoded['Date'] = df_encoded['Date'].map(mapp)

In [ ]:
df_encoded

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,Dec,0.189439,-0.047189,-0.206727,0.339244,0.675486,0.572085,0.111853,-1.401624,-1.460486,...,0,0,0,0,0,0,0,0,1,0
1,Dec,-0.747703,0.262022,-0.277606,0.339244,-1.124887,0.351004,-1.290058,-1.258211,-1.044802,...,0,0,0,0,0,0,0,0,0,1
2,Dec,0.111344,0.346352,-0.277606,0.486382,0.562962,0.793166,-1.601594,-1.019190,-1.474820,...,0,0,0,0,0,0,0,0,0,1
3,Dec,-0.466561,0.669618,-0.277606,-1.132137,-0.337224,-1.086022,-1.238135,-1.688449,-0.041427,...,0,0,0,0,0,0,0,0,0,0
4,Dec,0.829820,1.273985,-0.159474,0.118537,-0.787317,0.129923,0.683002,-0.875777,-1.016134,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,Jun,-1.356846,-0.201794,-0.277606,-0.617153,0.112869,-0.643860,-0.511218,-1.162602,0.976283,...,0,0,0,0,0,0,0,0,0,0
145455,Jun,-1.466179,0.023087,-0.277606,-0.617153,-0.112177,-0.864941,-0.926599,-1.306015,0.961949,...,0,0,0,0,0,0,0,0,0,0
145456,Jun,-1.341227,0.290132,-0.277606,-1.279275,-0.112177,-1.086022,-0.666986,-1.449428,0.804276,...,0,0,0,0,0,0,0,0,0,0
145457,Jun,-1.060084,0.515013,-0.277606,-0.175739,-0.562270,-1.086022,-0.822754,-1.306015,0.445927,...,0,0,0,0,0,0,0,0,1,0
145458,Jun,-0.685227,0.529068,-0.277606,-0.837861,-0.112177,-1.307103,-0.926599,-1.306015,0.216584,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
m=140787

In [ ]:
dt=['Date']

In [ ]:
df_encoded = pd.get_dummies(df_encoded, columns=dt)

In [ ]:
X=df_encoded.values

In [ ]:
X

array([[ 0.18943921, -0.04718855, -0.20672706, ...,  0.        ,
         0.        ,  0.        ],
       [-0.74770338,  0.26202222, -0.27760596, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.111344  ,  0.34635242, -0.27760596, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.34122703,  0.29013229, -0.27760596, ...,  0.        ,
         0.        ,  0.        ],
       [-1.06008425,  0.51501284, -0.27760596, ...,  0.        ,
         0.        ,  0.        ],
       [-0.68522721,  0.52906788, -0.27760596, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# Method 1: Using Python's list comprehension
theta= [0] * 123

In [ ]:
m=len(y)
m

140787

In [ ]:
X = np.hstack((np.ones((m,1)),X))

In [ ]:
X

array([[ 1.        ,  0.18943921, -0.04718855, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        , -0.74770338,  0.26202222, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  0.111344  ,  0.34635242, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.        , -1.34122703,  0.29013229, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        , -1.06008425,  0.51501284, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        , -0.68522721,  0.52906788, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [ ]:
import numpy as np
from scipy.special import expit
def sigmoid(g):
  hx = expit(g)
  return hx

In [ ]:

# def compute_ccost(y,theta,X):
#     theta_tr=np.transpose(theta)
#     g=X.dot(theta_tr)
#     hx=sigmoid(g)
    
#     # Compute the cost using the formula
#     log1=np.log(hx)
#     log2=np.log(1-hx)
#     a=np.dot((y),log1)
#     b=np.dot((1-y),log2)
#     cost=-a-b
#     #cost = -y * np.log(hx) - (1 - y) * np.log(1 - hx)
    
#     return cost

In [ ]:
from numpy import log,dot,e,shape

In [ ]:
def cost(y_train,theta,X_train):
  z = dot(X_train,theta)
  cost0 = y_train.T.dot(log(sigmoid(z)))
  cost1 = (1-y_train).T.dot(log(1-sigmoid(z)))
  cost = -((cost1 + cost0))/len(y_train) 
  return cost

In [ ]:
# def compute_cost(X, y, theta):
#     """
#      Compute the cost of a particular choice of theta for linear regression.

#      Input parameters
#      ----------------
#      X : 2D array where each row represent the training example and each column represents the feature ndarray. Dimension(m x n)
#          m = number of training examples
#          n = number of features (includes column of ones)
#      y : 1D array of labels/target value for each training example. Dimensions(1 x m)

#      theta: 1D array of fitting parameters. Dimensions(1 x n)

#      Output Parameters
#      -----------------
#      J : scalar value.
#      """
#     predictions = sigmoid(X.dot(theta))
#     #print ('prediction= ',predictions) 
#     # cost function for logistic regression
#     J = (-1)*(1/m)*np.sum((np.transpose(y)*np.log(predictions),np.transpose(1-y)*np.log(1-predictions)))


#     return J

In [ ]:
def gradient_descent(X_train, y_train, theta, alpha, iterations):
    theta_tr=np.transpose(theta)
    cost_history = np.zeros(iterations)
    
    for i in range(iterations):
        # print('theta= ',theta)
        g = X_train.dot(theta_tr)
        hx=sigmoid(g)
        # print('predictions= ',predictions)
        errors = np.subtract(hx,y_train)
        # print('errors =',errors)
        sum_delta = (alpha/m)*X_train.transpose().dot(errors)
        # print('sum_delta =',sum_delta)
        theta = np.subtract(theta,sum_delta)
        
        cost_history[i] = cost(y_train, theta,X_train )
    return theta, cost_history

In [ ]:
alpha=0.01
iterations=400

In [ ]:
theta, cost_history = gradient_descent(X_train, y_train, theta, alpha, iterations)
print('Final value of theta =\n ', theta)
print('First 5 values from cost_history =', cost_history[:5])
print('Last 5 values from cost_history =', cost_history[-5:])

Final value of theta =
  [-0.8932785   0.10817233 -0.21457721  0.31759367  0.28870984  0.12010829
  0.11732389  0.33535239  0.57885791 -0.30681815 -0.28365533 -0.03819231
 -0.25717872 -0.02535745 -0.0196467  -0.01389333 -0.01997344 -0.02897995
 -0.01974614 -0.0167345  -0.02118093 -0.01912108 -0.01262901 -0.02444828
 -0.02515857 -0.01372286 -0.01251536 -0.01755844 -0.01562644 -0.01944782
 -0.01191871 -0.01846761 -0.01377968 -0.01902164 -0.02673542 -0.02370958
 -0.01368024 -0.01413483 -0.0174732  -0.01223124 -0.0148025  -0.01251536
 -0.02075476 -0.02081158 -0.0206127  -0.02153608 -0.02155029 -0.00846669
 -0.02074055 -0.01927735 -0.02278619 -0.01853864 -0.01674871 -0.02275778
 -0.02083999 -0.01468886 -0.02241684 -0.01024242 -0.01765788 -0.01412062
 -0.01349556 -0.01700441 -0.02937771 -0.07220837 -0.06173865 -0.05732063
 -0.04807262 -0.05031715 -0.04020258 -0.03355423 -0.04008893 -0.05643987
 -0.06725053 -0.06342915 -0.05537443 -0.06067322 -0.09103113 -0.04078502
 -0.05479199 -0.07577404 -0.05963619 -0.06413944 -0.05446526 -0.05453629
 -0.04575707 -0.03682158 -0.05317252 -0.06260521 -0.07577404 -0.07020535
 -0.05125473 -0.05646828 -0.0487545  -0.04069978 -0.04321422 -0.06216483
 -0.05607052 -0.06386953 -0.04459219 -0.05787466 -0.03777337 -0.03865414
 -0.04345572 -0.06239212 -0.080533   -0.06442356 -0.05152464 -0.06798923
 -0.05557331 -0.04636792 -0.06001975 -0.07242146 -0.06663968 -0.07141284
 -0.06858588 -0.09185507 -0.06198015 -0.06679594 -0.08581758 -0.08189677
 -0.07405513 -0.08236556 -0.06945244]
First 5 values from cost_history = [0.69158744 0.69003319 0.68848445 0.68694119 0.68540344]
Last 5 values from cost_history = [0.41844999 0.41834284 0.41823738 0.4181336  0.4180315 ]

In [ ]:
cost_history

array([0.69158744, 0.69003319, 0.68848445, 0.68694119, 0.68540344,
       0.68387118, 0.68234441, 0.68082314, 0.67930736, 0.67779707,
       0.67629227, 0.67479295, 0.67329913, 0.67181079, 0.67032793,
       0.66885055, 0.66737865, 0.66591223, 0.66445127, 0.66299579,
       0.66154578, 0.66010123, 0.65866214, 0.65722851, 0.65580033,
       0.6543776 , 0.65296033, 0.65154849, 0.6501421 , 0.64874113,
       0.64734561, 0.6459555 , 0.64457082, 0.64319156, 0.64181771,
       0.64044927, 0.63908623, 0.63772858, 0.63637633, 0.63502947,
       0.63368799, 0.63235188, 0.63102115, 0.62969577, 0.62837576,
       0.6270611 , 0.62575178, 0.62444781, 0.62314916, 0.62185585,
       0.62056785, 0.61928516, 0.61800779, 0.61673571, 0.61546892,
       0.61420741, 0.61295119, 0.61170023, 0.61045454, 0.6092141 ,
       0.6079789 , 0.60674895, 0.60552422, 0.60430472, 0.60309043,
       0.60188135, 0.60067747, 0.59947878, 0.59828527, 0.59709693,
       0.59591375, 0.59473573, 0.59356285, 0.59239512, 0.5912325 ,
       0.59007501, 0.58892263, 0.58777535, 0.58663315, 0.58549604,
       0.584364  , 0.58323702, 0.5821151 , 0.58099821, 0.57988636,
       0.57877953, 0.57767772, 0.5765809 , 0.57548908, 0.57440224,
       0.57332037, 0.57224346, 0.5711715 , 0.57010449, 0.5690424 ,
       0.56798523, 0.56693296, 0.5658856 , 0.56484312, 0.56380552,
       0.56277278, 0.56174489, 0.56072185, 0.55970364, 0.55869025,
       0.55768166, 0.55667788, 0.55567888, 0.55468465, 0.55369519,
       0.55271048, 0.55173051, 0.55075526, 0.54978474, 0.54881892,
       0.54785779, 0.54690134, 0.54594956, 0.54500244, 0.54405997,
       0.54312213, 0.54218891, 0.54126031, 0.5403363 , 0.53941687,
       0.53850202, 0.53759173, 0.53668599, 0.53578478, 0.5348881 ,
       0.53399594, 0.53310827, 0.53222509, 0.53134639, 0.53047214,
       0.52960235, 0.528737  , 0.52787607, 0.52701955, 0.52616744,
       0.52531971, 0.52447636, 0.52363736, 0.52280272, 0.52197242,
       0.52114644, 0.52032477, 0.51950741, 0.51869432, 0.51788552,
       0.51708097, 0.51628067, 0.51548461, 0.51469277, 0.51390514,
       0.5131217 , 0.51234245, 0.51156737, 0.51079646, 0.51002968,
       0.50926704, 0.50850852, 0.50775411, 0.50700379, 0.50625755,
       0.50551538, 0.50477727, 0.5040432 , 0.50331316, 0.50258714,
       0.50186512, 0.5011471 , 0.50043305, 0.49972297, 0.49901684,
       0.49831465, 0.49761639, 0.49692204, 0.49623159, 0.49554504,
       0.49486235, 0.49418354, 0.49350857, 0.49283744, 0.49217013,
       0.49150664, 0.49084694, 0.49019103, 0.48953889, 0.48889052,
       0.48824589, 0.487605  , 0.48696783, 0.48633437, 0.48570461,
       0.48507853, 0.48445612, 0.48383737, 0.48322227, 0.4826108 ,
       0.48200296, 0.48139872, 0.48079808, 0.48020102, 0.47960753,
       0.4790176 , 0.47843122, 0.47784837, 0.47726904, 0.47669322,
       0.4761209 , 0.47555206, 0.47498669, 0.47442478, 0.47386631,
       0.47331128, 0.47275967, 0.47221147, 0.47166667, 0.47112526,
       0.47058721, 0.47005253, 0.4695212 , 0.4689932 , 0.46846853,
       0.46794716, 0.4674291 , 0.46691433, 0.46640283, 0.4658946 ,
       0.46538962, 0.46488788, 0.46438936, 0.46389407, 0.46340197,
       0.46291307, 0.46242736, 0.46194481, 0.46146541, 0.46098916,
       0.46051605, 0.46004606, 0.45957918, 0.4591154 , 0.4586547 ,
       0.45819708, 0.45774253, 0.45729102, 0.45684256, 0.45639713,
       0.45595472, 0.45551531, 0.4550789 , 0.45464547, 0.45421502,
       0.45378753, 0.45336299, 0.45294138, 0.45252271, 0.45210695,
       0.4516941 , 0.45128415, 0.45087707, 0.45047287, 0.45007153,
       0.44967305, 0.4492774 , 0.44888458, 0.44849458, 0.44810739,
       0.44772299, 0.44734138, 0.44696254, 0.44658647, 0.44621315,
       0.44584258, 0.44547474, 0.44510961, 0.44474721, 0.4443875 ,
       0.44403048, 0.44367614, 0.44332447, 0.44297546, 0.4426291 ,
       0.44228538, 0.44194429, 0.44160581, 0.44126994, 0.44093667,
       0.44060599, 0.44027788, 0.43995235, 0.43962937, 0.43930893,
       0.43899104, 0.43867567, 0.43836282, 0.43805247, 0.43774463,
       0.43743927, 0.43713639, 0.43683598, 0.43653803, 0.43624253,
       0.43594946, 0.43565883, 0.43537062, 0.43508482, 0.43480142,
       0.43452041, 0.43424178, 0.43396553, 0.43369164, 0.4334201 ,
       0.43315091, 0.43288406, 0.43261953, 0.43235732, 0.43209742,
       0.43183981, 0.4315845 , 0.43133147, 0.43108071, 0.43083221,
       0.43058597, 0.43034197, 0.4301002 , 0.42986067, 0.42962335,
       0.42938824, 0.42915533, 0.42892462, 0.42869609, 0.42846973,
       0.42824554, 0.4280235 , 0.42780362, 0.42758587, 0.42737026,
       0.42715677, 0.42694539, 0.42673613, 0.42652896, 0.42632387,
       0.42612087, 0.42591995, 0.42572109, 0.42552428, 0.42532952,
       0.42513681, 0.42494612, 0.42475746, 0.42457082, 0.42438618,
       0.42420355, 0.4240229 , 0.42384424, 0.42366756, 0.42349284,
       0.42332009, 0.42314928, 0.42298042, 0.4228135 , 0.42264851,
       0.42248544, 0.42232429, 0.42216504, 0.42200768, 0.42185222,
       0.42169865, 0.42154695, 0.42139712, 0.42124915, 0.42110303,
       0.42095876, 0.42081633, 0.42067573, 0.42053696, 0.4204    ,
       0.42026485, 0.4201315 , 0.41999996, 0.41987019, 0.41974221,
       0.41961601, 0.41949157, 0.41936889, 0.41924796, 0.41912878,
       0.41901134, 0.41889564, 0.41878165, 0.41866939, 0.41855883,
       0.41844999, 0.41834284, 0.41823738, 0.4181336 , 0.4180315 ])

In [ ]:
# for 
# cost_history_f = cost(X_test, y_test, theta, alpha, iterations)
# #print('Final value of theta =\n ', theta)
#   print('First 5 values from cost_history =', cost_history[:5])
#   print('Last 5 values from cost_history =', cost_history[-5:])

In [ ]:
predictions= dot(X_test,theta)
predictions=sigmoid(predictions)

for i in range(len(predictions)):
    if(predictions[i]>=0.5):
        predictions[i]=1
    else:
        predictions[i]=0

In [ ]:
predictions

array([0., 0., 1., ..., 1., 0., 1.])

In [ ]:
acc=0

In [ ]:
for i in range(len(y_test)):
    if(y_test[i]==predictions[i]):
        acc=acc+1
    else:
        acc=acc
accuracy=(acc/len(y_test))*100

In [ ]:
print("The accuracy of your model is",accuracy,"%")

The accuracy of your model is 81.91632928475033 %